### ISSUE TITLE
1.0.14: TypeError: this.autocomplete.removeListener is not a function

### ISSUE THREAD

**Issue by torte** [ErrorPro/react-google-autocomplete#19]
After updating to 1.0.14 I am getting the above error in the console when unmounting the component. Most like related to changes from https://github.com/ErrorPro/react-google-autocomplete/commit/f89fb0f10710520b8caaa2961975498e3b4dead5.

**Comment by MeXaaR** [comment]
Same error

**Comment by cicer1** [comment]
Same error also for me

**Comment by ErrorPro** [comment]
Checking it out guys.

**Comment by ErrorPro** [comment]
Fixed in 0.15, check it out please.

**Comment by MeXaaR** [comment]
great !! thanks, it works. Thanks you for your reactivity  ;)

**Comment by torte** [comment]
Thank you very much.
